server:
  port: 8081
  servlet:
    context-path: /ehcache

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.103:3306/ehcache?characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&failOverReadOnly=false&connectTimeout=6000&maxReconnects=5
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
